channels:
  - conda-forge
  - defaults
dependencies:
  - basemap
  - bokeh
  - boto3
  - contextily
  - folium
  - fsspec
  - gdal
  - geopandas
  - geoviews
  - geoviews-core
  - gh-scoped-creds
  - ghp-import
  - h5py
  - holoviews
  - hvplot
  - imageio
  - ipykernel
  - ipyleaflet
  - ipympl
  - ipython
  - jupyter_bokeh
  - jupyter-book
  - jupyter-server-proxy[version='>=4.1.1']
  - jupyterhub-singleuser
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-myst
  - jupytext
  - leafmap
  - localtileserver
  - lxml
  - matplotlib
  - nbgitpuller[version='>=1.2.1']
  - nodejs
  - notebook
  - numba
  - numexpr[version='>=2.8.7']
  - numpy
  - panel
  - pystac-client
  - python[version='>=3.12']]
  - rasterio
  - requests
  - rioxarray
  - s3fs
  - scikit-image
  - selenium
  - xarray
